# Generated by Django 2.0.2 on 2018-03-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.BigIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Semester', models.IntegerField()),
                ('Section', models.CharField(max_length=1)),
            ],
        ),
    ]
