# Generated by Django 2.0.2 on 2018-03-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='info_table',
            name='rollno',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
