# Generated by Django 2.0.2 on 2018-03-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
